''' Even Fibonacci numbers
Problem 2

Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
'''
def fibonacci_sequence(maximum):
    fibs = [1,1]
    while (fibs[-1]+ fibs[-2])<maximum:
        fibs.append(fibs[-2] + fibs[-1])
    return fibs
def sum_even_from_list(num_list):
    number_holder = 0
    for num in num_list:
        if num % 2 == 0:
            number_holder = num + number_holder
    return number_holder
print(sum_even_from_list(fibonacci_sequence(4000000)))